# --- CONFIGURACOES DO SERVIDOR ---
server.port=8080

# --- CONFIGURACOES DO BANCO DE DADOS (SQL SERVER) ---
spring.datasource.url=jdbc:sqlserver://SRV-B03:1433;databaseName=Auditoria;encrypt=true;trustServerCertificate=true;
spring.datasource.username=auditoria
spring.datasource.password=MasteR@20210325%
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

# --- CONFIGURACOES DO JPA / HIBERNATE ---
# Define como o Java lida com as tabelas (none = nao altera a estrutura do banco)
spring.jpa.hibernate.ddl-auto=none
# Mostra no console as consultas SQL que o Java esta fazendo
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Impede o Spring de colocar sublinhados (_) e obriga a usar o nome exato do codigo (ex: colCodigo)
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
